Repository AY2122S1-CS2103T-T09-1/tp, pull requests merged in 2021-11, with the labels that each got.

#187 Display relevant error message for tags with spaces
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/tag/Tag.java
Labels: ✅ Ready to merge

#189 Update UG based on PE-D feedback
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/model/amenity/Amenity.java
Labels: ✅ Ready to merge

#169 Add emojis to command output, edit UG
  docs/UserGuide.md
  src/main/java/seedu/address/model/amenity/Amenity.java
  src/main/java/seedu/address/model/studyspot/Favourite.java
  src/main/java/seedu/address/model/studyspot/Rating.java
  src/main/java/seedu/address/model/studyspot/StudySpot.java
  src/main/java/seedu/address/model/tag/Tag.java
Labels: ✅ Ready to merge

#212 Improve clarity of Find Command in UG
  docs/UserGuide.md
Labels: type.documentation, priority.Low, ✅ Ready to merge

#211 Fix Integer Overflow in PieChart
  src/main/java/seedu/address/ui/InfoDisplay.java
Labels: type.Bug, severity.Low, ✅ Ready to merge

#215 Revert emoji changes
  src/main/java/seedu/address/model/amenity/Amenity.java
  src/main/java/seedu/address/model/studyspot/Favourite.java
  src/main/java/seedu/address/model/studyspot/Rating.java
  src/main/java/seedu/address/model/studyspot/StudySpot.java
  src/main/java/seedu/address/model/tag/Tag.java
Labels: ✅ Ready to merge

#213 Fix operating hours
  docs/UserGuide.md
  src/main/java/seedu/address/model/studyspot/OperatingHours.java
  src/test/java/seedu/address/model/studyspot/OperatingHoursTest.java
Labels: type.Bug, severity.Medium, ✅ Ready to merge

#183 Display error message for invalid Log Commands
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/LogCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AliasCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/LogCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/UnaliasCommandParser.java
  src/test/java/seedu/address/logic/parser/LogCommandParserTest.java
Labels: ✅ Ready to merge

#219 PED: Improve clarity of UG
  docs/UserGuide.md
Labels: type.documentation, ✅ Ready to merge

#225 Add mslevis PPP
  docs/AboutUs.md
  docs/images/mslevis.png
  docs/team/johndoe.md
  docs/team/mslevis.md
Labels: type.documentation, ✅ Ready to merge

#216 Add Joenz PPP
  docs/AboutUs.md
  docs/images/joenzkimchan.png
  docs/team/joenzkimchan.md
Labels: type.documentation, priority.Medium, severity.VeryLow, ✅ Ready to merge

#218 PED: Fix long tags
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/model/tag/TagTest.java
Labels: type.Bug, severity.VeryLow, ✅ Ready to merge

#226 add ruoyann PPP
  docs/AboutUs.md
  docs/images/ruoyan.png
  docs/images/ruoyann.png
  docs/team/ruoyann.md
Labels: ✅ Ready to merge

#223 Add acknowledgements in docs
  README.md
  copyright.txt
  docs/index.md
  src/main/resources/images/address_book_32.png
  src/main/resources/images/calendar.png
  src/main/resources/images/clock.png
  src/main/resources/images/fail.png
Labels: type.documentation, ✅ Ready to merge

#227 Add limdanqi PPP
  docs/AboutUs.md
  docs/images/limdanqi.png
  docs/team/limdanqi.md
Labels: type.documentation, ✅ Ready to merge

#221 Improve test coverage
  src/main/java/seedu/address/logic/commands/AliasCommand.java
  src/test/java/seedu/address/AppParametersTest.java
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/logic/commands/AliasCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/util/CommandListTest.java
  src/test/java/seedu/address/model/StudyTrackerTest.java
  src/test/java/seedu/address/model/alias/AliasTest.java
  src/test/java/seedu/address/model/studyspot/AddressTest.java
  src/test/java/seedu/address/model/studyspot/NameTest.java
  src/test/java/seedu/address/model/studyspot/OperatingHoursTest.java
  src/test/java/seedu/address/model/studyspot/RatingTest.java
  src/test/java/seedu/address/model/studyspot/StudySpotTest.java
  src/test/java/seedu/address/model/studyspot/UniqueStudySpotListTest.java
Labels: type.Enhancement, ✅ Ready to merge

#224 Increase code coverage
  src/main/java/seedu/address/logic/commands/LogCommand.java
  src/main/java/seedu/address/logic/parser/LogCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/LogCommandTest.java
  src/test/java/seedu/address/logic/parser/LogCommandParserTest.java
Labels: priority.Low, ✅ Ready to merge

#217 PED: Fix Alias not parsing flags
  src/main/java/seedu/address/logic/parser/AliasCommandParser.java
  src/test/java/seedu/address/logic/parser/AliasCommandParserTest.java
Labels: type.Bug, severity.Medium, ✅ Ready to merge

#235 UG DG Fixes
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ParserClasses.png
  src/main/java/seedu/address/logic/commands/LogCommand.java
Labels: ✅ Ready to merge

#230 Improve test coverage in Logic
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/studyspot/StudiedHours.java
  src/test/data/JsonSerializableStudyTrackerTest/typicalStudySpotsStudyTracker.json
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/studyspot/StudiedHoursTest.java
  src/test/java/seedu/address/model/studyspot/StudySpotTest.java
  src/test/java/seedu/address/testutil/TypicalStudySpots.java
Labels: type.Task, ✅ Ready to merge

#228 Fix outdated images in User Guide
  docs/UserGuide.md
  docs/images/add_favourites.png
  docs/images/list_tags_amenities.png
  docs/images/list_tags_cold.png
Labels: ✅ Ready to merge

#238 Improve coverage of StudyTrackerParser
  src/test/java/seedu/address/logic/parser/StudyTrackerParserTest.java
Labels: ✅ Ready to merge

#220 Modify file path of preferences.json
  src/main/java/seedu/address/commons/core/Config.java
  src/test/data/ConfigUtilTest/ExtraValuesConfig.json
  src/test/data/ConfigUtilTest/TypicalConfig.json
  src/test/data/JsonSerializableUserPrefsTest/duplicateAliasesUserPrefs.json
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/commons/util/ConfigUtilTest.java
Labels: type.Task, priority.Low, ✅ Ready to merge

#234 Improve coverage of EditCommandParser
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
Labels: ✅ Ready to merge

#233 Improve coverage of DeleteCommandParser
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: ✅ Ready to merge

#229 Fix some discrepancies in the UG
  docs/UserGuide.md
  src/test/java/seedu/address/commons/core/ConfigTest.java
Labels: ✅ Ready to merge

#242 Increase Amenity Coverage
  src/test/java/seedu/address/model/amenity/AmenityTest.java
Labels: ✅ Ready to merge

#241 Increase Edit Command coverage
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: ✅ Ready to merge

#244 Destroy Commands and Command parsers in Sequence Diagrams
  docs/diagrams/AddOperatingHoursSequenceDiagram.puml
  docs/diagrams/AliasSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/EditRemoveTagSequenceDiagram.puml
  docs/diagrams/ListSequenceDiagram.puml
  docs/diagrams/LogSequenceDiagram.puml
  docs/diagrams/LogSequenceDiagramWithFlagO.puml
  docs/images/AddOperatingHoursSequenceDiagram.png
  docs/images/AliasSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/EditRemoveTagSequenceDiagram.png
  docs/images/ListSequenceDiagram.png
  docs/images/LogSequenceDiagram.png
  docs/images/LogSequenceDiagramWithFlagO.png
Labels: ✅ Ready to merge

#239 Update README.md
  README.md
Labels: ✅ Ready to merge

#240 Increase Log Command Coverage
  src/test/java/seedu/address/logic/commands/LogCommandTest.java
Labels: ✅ Ready to merge

#245 Reorder sections in DG - features
  docs/DeveloperGuide.md
Labels: ✅ Ready to merge

#236 Improve coverage for ParserUtil
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: ✅ Ready to merge

#246 Fix inconsistencies in UGDG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.documentation, ✅ Ready to merge

#249 Check if UG can be followed through
  docs/UserGuide.md
  docs/images/list_tags_amenities.png
Labels: ✅ Ready to merge

#247 Update UG - Add Glossary, Command History
  docs/UserGuide.md
Labels: type.documentation, ✅ Ready to merge

#250 Add amenity sequence diagram
  docs/DeveloperGuide.md
  docs/diagrams/AddAmenitySequenceDiagram.puml
Labels: type.documentation, ✅ Ready to merge

#253 Add activity diagram for List Command
  docs/DeveloperGuide.md
  docs/diagrams/ListCommandActivityDiagram.puml
  docs/images/ListCommandActivityDiagram.png
Labels: type.documentation, ✅ Ready to merge

#252 Reordering of clear before help feature
  docs/UserGuide.md
Labels: type.documentation, ✅ Ready to merge

#255 SLAP InfoDisplay.java, add comments to some methods in log command
  src/main/java/seedu/address/logic/commands/LogCommand.java
  src/main/java/seedu/address/ui/InfoDisplay.java
Labels: severity.Low, ✅ Ready to merge

#254 Code quality
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AliasCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FavouriteCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/LogCommand.java
  src/main/java/seedu/address/logic/commands/UnaliasCommand.java
  src/main/java/seedu/address/logic/commands/UnfavouriteCommand.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/logic/parser/LogCommandParser.java
  src/test/java/seedu/address/logic/parser/LogCommandParserTest.java
Labels: type.Task, ✅ Ready to merge

#251 Improve parseFlags test in ParserUtil
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: ✅ Ready to merge

#258 Update version
  src/main/java/seedu/address/MainApp.java
Labels: ✅ Ready to merge

#257 Improve DG Page Break
  docs/DeveloperGuide.md
Labels: ✅ Ready to merge

#261 Increase default width of StudyTracker
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
Labels: type.Enhancement, ✅ Ready to merge

#259 Fix Tables in UG
  docs/UserGuide.md
Labels: ✅ Ready to merge

#260 Fix bug with user preferences
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/storage/JsonUserPrefsStorage.java
Labels: type.Bug, severity.Medium, ✅ Ready to merge

#265 Include back to top button
  docs/UserGuide.md
Labels: ✅ Ready to merge

#266 Fix broken links
  docs/UserGuide.md
  docs/index.md
Labels: priority.High, ✅ Ready to merge

#267 Minor changes to UG
  docs/UserGuide.md
Labels: ✅ Ready to merge

#268 Fix link
  docs/UserGuide.md
Labels: ✅ Ready to merge
