Repository AY2122S1-CS2103T-T09-1/tp, pull requests merged in 2021-10, with the labels that each got.

#51 Add more tests for EditCommand
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: ✅ Ready to merge

#52 Upgrade Gui to have Ratings
  copyright.txt
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Version.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/java/seedu/address/ui/StudySpotCard.java
  src/main/java/seedu/address/ui/StudySpotListPanel.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/Main.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/StudySpotListCard.fxml
  src/main/resources/view/StudySpotListPanel.fxml
  src/test/java/seedu/address/commons/core/VersionTest.java
Labels: type.Enhancement, priority.Medium

#55 Fix StudyTrackerParserTest parseCommand_Edit
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/java/seedu/address/logic/parser/StudyTrackerParserTest.java
  src/test/java/seedu/address/testutil/EditStudySpotDescriptorBuilder.java
  src/test/java/seedu/address/testutil/StudySpotUtil.java
Labels: ✅ Ready to merge

#61 Update StudySpot Count Gui
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StudySpotListPanel.java
  src/main/resources/view/StudySpotListPanel.fxml
Labels: type.Enhancement, priority.Medium, ✅ Ready to merge

#59 Implement Add favourites
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FavouriteCommand.java
  src/main/java/seedu/address/logic/commands/UnfavouriteCommand.java
  src/main/java/seedu/address/logic/parser/FavouriteCommandParser.java
  src/main/java/seedu/address/logic/parser/StudyTrackerParser.java
  src/main/java/seedu/address/logic/parser/UnfavouriteCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyStudyTracker.java
  src/main/java/seedu/address/model/StudyTracker.java
  src/main/java/seedu/address/model/studyspot/Favourite.java
  src/main/java/seedu/address/model/studyspot/StudySpot.java
  src/main/java/seedu/address/storage/JsonAdaptedStudySpot.java
  src/main/java/seedu/address/ui/StudySpotCard.java
  src/main/resources/view/StudySpotListCard.fxml
  src/test/data/JsonSerializableStudyTrackerTest/duplicateStudySpotStudyTracker.json
  src/test/data/JsonSerializableStudyTrackerTest/invalidStudySpotStudyTracker.json
  src/test/data/JsonSerializableStudyTrackerTest/typicalStudySpotsStudyTracker.json
  src/test/data/JsonStudyTrackerStorageTest/invalidAndValidStudySpotStudyTracker.json
  src/test/data/JsonStudyTrackerStorageTest/invalidStudySpotStudyTracker.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FavouriteCommandTest.java
  src/test/java/seedu/address/logic/commands/UnfavouriteCommandTest.java
  src/test/java/seedu/address/logic/parser/FavouriteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/StudyTrackerParserTest.java
  src/test/java/seedu/address/logic/parser/UnfavouriteCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/StudyTrackerTest.java
  src/test/java/seedu/address/model/studyspot/FavouriteTest.java
  src/test/java/seedu/address/model/studyspot/StudySpotTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudySpotTest.java
  src/test/java/seedu/address/testutil/StudySpotBuilder.java
Labels: priority.High, ✅ Ready to merge

#63 Cleanup addressbooks in tests
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/data/JsonSerializableStudyTrackerTest/typicalStudySpotsStudyTracker.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/storage/JsonStudyTrackerStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/StudyTrackerBuilder.java
Labels: priority.Low, ✅ Ready to merge

#64 Update UG for find, fav, unfav
  docs/UserGuide.md
Labels: priority.Medium, ✅ Ready to merge

#72 Edit Amenities Output
  src/main/java/seedu/address/model/amenity/Amenity.java
Labels: ✅ Ready to merge

#80 Tidy up Amenities Gui code
  src/main/java/seedu/address/ui/StudySpotCard.java
  src/main/resources/view/Main.css
  src/main/resources/view/StudySpotListCard.fxml
Labels: type.Enhancement, ✅ Ready to merge

#85 Implement themes
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/SettingsWindow.java
  src/main/java/seedu/address/ui/StudySpotCard.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/styles/Extensions.css
  src/main/resources/styles/Fonts.css
  src/main/resources/styles/HelpWindow.css
  src/main/resources/styles/Main.css
  src/main/resources/styles/ThemeAb3.css
  src/main/resources/styles/ThemeDefault.css
  src/main/resources/styles/ThemeDotsdark.css
  src/main/resources/styles/ThemeDotslight.css
  src/main/resources/styles/ThemeMilkshake.css
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/SettingsWindow.fxml
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/InvalidValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: type.Story, type.Enhancement, priority.Medium, ✅ Ready to merge

#91 Fix Table of Contents
  docs/DeveloperGuide.md
Labels: type.documentation, type.Bug, ✅ Ready to merge

#90 Add Operating Hours
  docs/tutorials/RemovingFields.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/StudyTracker.java
  src/main/java/seedu/address/model/studyspot/Email.java
  src/main/java/seedu/address/model/studyspot/OperatingHours.java
  src/main/java/seedu/address/model/studyspot/StudySpot.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedStudySpot.java
  src/main/java/seedu/address/ui/StudySpotCard.java
  src/main/resources/view/StudySpotListCard.fxml
  src/test/data/JsonSerializableStudyTrackerTest/duplicateStudySpotStudyTracker.json
  src/test/data/JsonSerializableStudyTrackerTest/invalidStudySpotStudyTracker.json
  src/test/data/JsonSerializableStudyTrackerTest/typicalStudySpotsStudyTracker.json
  src/test/data/JsonStudyTrackerStorageTest/invalidAndValidStudySpotStudyTracker.json
  src/test/data/JsonStudyTrackerStorageTest/invalidStudySpotStudyTracker.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditStudySpotDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/studyspot/EmailTest.java
  src/test/java/seedu/address/model/studyspot/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/studyspot/OperatingHoursTest.java
  src/test/java/seedu/address/model/studyspot/StudySpotTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudySpotTest.java
  src/test/java/seedu/address/storage/JsonSerializableStudyTrackerTest.java
  src/test/java/seedu/address/testutil/EditStudySpotDescriptorBuilder.java
  src/test/java/seedu/address/testutil/StudySpotBuilder.java
  src/test/java/seedu/address/testutil/StudySpotUtil.java
  src/test/java/seedu/address/testutil/TypicalStudySpots.java
Labels: type.Enhancement, priority.Medium, ✅ Ready to merge

#92 Beautify Help window
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/util/CommandList.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/alias/Alias.java
  src/main/java/seedu/address/ui/HelpCommandInfoDisplay.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/styles/Main.css
  src/main/resources/view/HelpCommandInfoDisplay.fxml
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/StudySpotListPanel.fxml
Labels: type.Enhancement, ✅ Ready to merge

#96 Include Alias implementation in DG
  docs/DeveloperGuide.md
  docs/diagrams/AliasActivityDiagram.puml
  docs/diagrams/AliasSequenceDiagram.puml
  docs/diagrams/AliasState0.puml
  docs/diagrams/AliasState1.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/AliasActivityDiagram.png
  docs/images/AliasSequenceDiagram.png
  docs/images/AliasState0.png
  docs/images/AliasState1.png
Labels: type.documentation, priority.Medium, ✅ Ready to merge

#109 Update DG - Logic
  docs/DeveloperGuide.md
  docs/diagrams/AliasSequenceDiagram.puml
  docs/diagrams/ListSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/ListSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ParserClasses.png
Labels: type.documentation, priority.High, ✅ Ready to merge

#111 Reformat command syntax
  docs/UserGuide.md
Labels: type.documentation, priority.High, ✅ Ready to merge

#115 Update DG - Enhanced Edit Command
  docs/DeveloperGuide.md
  docs/diagrams/EditRemoveTagSequenceDiagram.puml
  docs/images/EditRemoveTagSequenceDiagram.png
Labels: type.documentation, priority.Medium, ✅ Ready to merge

#207 Remove studyspot from fav list if it's deleted before unfaving
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
Labels: ✅ Ready to merge

#198 Making add case insensitive
  src/main/java/seedu/address/model/studyspot/StudySpot.java
  src/main/java/seedu/address/ui/InfoDisplay.java
  src/test/java/seedu/address/model/studyspot/StudySpotTest.java
Labels: ✅ Ready to merge

#188 Allow 0 as a rating
  src/main/java/seedu/address/model/studyspot/Rating.java
  src/test/java/seedu/address/model/studyspot/RatingTest.java
Labels: ✅ Ready to merge
